export const ALL_PRODUCTS_LIST_REQUEST = "ALL_PRODUCTS_LIST_REQUEST";
export const ALL_PRODUCTS_LIST_SUCCESS = "ALL_PRODUCTS_LIST_SUCCESS";
export const ALL_PRODUCTS_LIST_FAIL = "ALL_PRODUCTS_LIST_FAIL";

export const PRODUCT_BY_ID_REQUEST = "PRODUCT_BY_ID_REQUEST";
export const PRODUCT_BY_ID_SUCCESS = "PRODUCT_BY_ID_SUCCESS";
export const PRODUCT_BY_ID_FAIL = "PRODUCT_BY_ID_FAIL";
